site_name: "Virtual Chemistry Lab Manual: A Computational Approach"
site_url: https://lab.chemis.fun
theme:
  name: material
  font: 
    text: Roboto
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: https://chemis.fun/assets/images/chemisfun-logo.png
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/

copyright: Copyright &copy; 2025 Xinyue Wang, All Rights Reserved.